name: PracticePvP
main: com.creamint.practice.PracticePvP
version: 1.0
api-version: 1.16
commands:
  mashiprac:
    description: Main command for PracticePvP
  event:
    description: Command to select and join events
  duel:
    description: Command to send duel requests
  spec:
    description: Command to spectate a player
  stats:
    description: Command to view player stats
  l:
    description: Command to leave the current match and return to the lobby
  event join:
    description: Command to join an ongoing event
  party create:
    description: Command to create a party
  party invite:
    description: Command to invite a player to a party
  party setlimit:
    description: Command to set the party limit
  party promote:
    description: Command to promote a player to party leader
  party leave:
    description: Command to leave the current party
  party disband:
    description: Command to disband the current party