name: PracticePvP
main: com.creamint.practice.PracticePvP
version: 1.0
api-version: 1.8
author: CreaMint-Dev
commands:
  mashiprac:
    description: Main command for PracticePvP
    usage: /mashiprac
  event:
    description: Event command
    usage: /event
  duel:
    description: Duel command
    usage: /duel
  spec:
    description: Spectate command
    usage: /spec
  stats:
    description: Stats command
    usage: /stats
  l:
    description: Leave command
    usage: /l
  event join:
    description: Join event command
    usage: /event join
  arena:
    description: Arena command
    usage: /arena
  kit:
    description: Kit command
    usage: /kit